import '@styles/globals.css'
import type { Metadata } from 'next'
import { Content, Inter } from 'next/font/google' 
import styles from './page.module.css'
import Providers from '@/redux/store/Provider';
import NavBar from '@components/navigation-bar/NavBar'
import Link from 'next/link'  
import Head from 'next/head';

import { Container, Typography, Link as MuiLink } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

type RootLayoutProps = {
  children: React.ReactNode;
};


export const metadata: Metadata = {
  title: 'OnlineShop',
  description: 'Generated by create next app', 
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {

  return (
    <html lang="en">  
      <body className={inter.className}>  
        <Providers> 
          <NavBar /> 
          <div>
            {children}
          </div> 
        </Providers>
        <footer className={styles.footer}> 
          <Container>
            <Typography variant="body1" align="center" style={{ fontSize: '14px' }}>
              <MuiLink href="#" target="_blank" color="inherit" underline="none">
                <span>Copyright 2023 Online Shop</span>
              </MuiLink>
            </Typography>
          </Container>
        </footer>
      </body>
    </html>
  )
}

export default RootLayout;